module layer_1
#(
  parameter
  DATA_WIDTH            = 16,
  WEIGHT_WIDTH          = 16,
  N_WEIGHTS             = 784,
  N_NEURONS             = 64,
  N_INPUTS              = 784,
  SIGMOID_INPUT_WIDTH   = 5,
  ACC_TYPE              = "reLU",
  BIAS_WIDTH            = 32
)
(
  input                               clk,
  input                               reset,
  input                               input_valid,
  input      [DATA_WIDTH-1:0]         input_value,
  output     [(DATA_WIDTH*N_NEURONS)-1:0] output_values,
  output                              outputs_valid,
  output                              layer_ready,
  input                               cfg_write_enable,
  input      [5:0]                    cfg_neuron,
  input      [9:0]                    cfg_index,
  input                               cfg_is_bias,
  input      [BIAS_WIDTH-1:0]         cfg_write_data
);

localparam WEIGHT_ADDRESS_WIDTH = $clog2(N_WEIGHTS);
wire [N_NEURONS-1:0] outputs_valid_array;
wire [N_NEURONS-1:0] neuron_ready_array;
assign outputs_valid = &outputs_valid_array;
assign layer_ready = &neuron_ready_array;


neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_0.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_0.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_0
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((0+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[0]),
    .neuron_ready(neuron_ready_array[0]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd0),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_1.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_1.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_1
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((1+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[1]),
    .neuron_ready(neuron_ready_array[1]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd1),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_2.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_2.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_2
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((2+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[2]),
    .neuron_ready(neuron_ready_array[2]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd2),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_3.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_3.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_3
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((3+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[3]),
    .neuron_ready(neuron_ready_array[3]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd3),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_4.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_4.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_4
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((4+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[4]),
    .neuron_ready(neuron_ready_array[4]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd4),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_5.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_5.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_5
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((5+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[5]),
    .neuron_ready(neuron_ready_array[5]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd5),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_6.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_6.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_6
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((6+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[6]),
    .neuron_ready(neuron_ready_array[6]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd6),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_7.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_7.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_7
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((7+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[7]),
    .neuron_ready(neuron_ready_array[7]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd7),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_8.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_8.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_8
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((8+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[8]),
    .neuron_ready(neuron_ready_array[8]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd8),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_9.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_9.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_9
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((9+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[9]),
    .neuron_ready(neuron_ready_array[9]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd9),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_10.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_10.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_10
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((10+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[10]),
    .neuron_ready(neuron_ready_array[10]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd10),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_11.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_11.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_11
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((11+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[11]),
    .neuron_ready(neuron_ready_array[11]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd11),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_12.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_12.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_12
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((12+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[12]),
    .neuron_ready(neuron_ready_array[12]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd12),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_13.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_13.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_13
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((13+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[13]),
    .neuron_ready(neuron_ready_array[13]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd13),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_14.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_14.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_14
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((14+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[14]),
    .neuron_ready(neuron_ready_array[14]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd14),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_15.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_15.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_15
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((15+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[15]),
    .neuron_ready(neuron_ready_array[15]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd15),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_16.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_16.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_16
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((16+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[16]),
    .neuron_ready(neuron_ready_array[16]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd16),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_17.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_17.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_17
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((17+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[17]),
    .neuron_ready(neuron_ready_array[17]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd17),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_18.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_18.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_18
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((18+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[18]),
    .neuron_ready(neuron_ready_array[18]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd18),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_19.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_19.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_19
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((19+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[19]),
    .neuron_ready(neuron_ready_array[19]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd19),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_20.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_20.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_20
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((20+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[20]),
    .neuron_ready(neuron_ready_array[20]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd20),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_21.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_21.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_21
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((21+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[21]),
    .neuron_ready(neuron_ready_array[21]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd21),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_22.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_22.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_22
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((22+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[22]),
    .neuron_ready(neuron_ready_array[22]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd22),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_23.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_23.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_23
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((23+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[23]),
    .neuron_ready(neuron_ready_array[23]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd23),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_24.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_24.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_24
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((24+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[24]),
    .neuron_ready(neuron_ready_array[24]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd24),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_25.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_25.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_25
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((25+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[25]),
    .neuron_ready(neuron_ready_array[25]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd25),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_26.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_26.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_26
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((26+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[26]),
    .neuron_ready(neuron_ready_array[26]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd26),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_27.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_27.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_27
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((27+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[27]),
    .neuron_ready(neuron_ready_array[27]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd27),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_28.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_28.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_28
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((28+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[28]),
    .neuron_ready(neuron_ready_array[28]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd28),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_29.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_29.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_29
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((29+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[29]),
    .neuron_ready(neuron_ready_array[29]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd29),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_30.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_30.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_30
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((30+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[30]),
    .neuron_ready(neuron_ready_array[30]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd30),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_31.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_31.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_31
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((31+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[31]),
    .neuron_ready(neuron_ready_array[31]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd31),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_32.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_32.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_32
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((32+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[32]),
    .neuron_ready(neuron_ready_array[32]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd32),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_33.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_33.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_33
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((33+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[33]),
    .neuron_ready(neuron_ready_array[33]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd33),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_34.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_34.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_34
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((34+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[34]),
    .neuron_ready(neuron_ready_array[34]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd34),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_35.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_35.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_35
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((35+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[35]),
    .neuron_ready(neuron_ready_array[35]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd35),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_36.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_36.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_36
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((36+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[36]),
    .neuron_ready(neuron_ready_array[36]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd36),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_37.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_37.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_37
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((37+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[37]),
    .neuron_ready(neuron_ready_array[37]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd37),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_38.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_38.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_38
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((38+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[38]),
    .neuron_ready(neuron_ready_array[38]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd38),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_39.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_39.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_39
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((39+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[39]),
    .neuron_ready(neuron_ready_array[39]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd39),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_40.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_40.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_40
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((40+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[40]),
    .neuron_ready(neuron_ready_array[40]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd40),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_41.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_41.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_41
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((41+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[41]),
    .neuron_ready(neuron_ready_array[41]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd41),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_42.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_42.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_42
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((42+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[42]),
    .neuron_ready(neuron_ready_array[42]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd42),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_43.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_43.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_43
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((43+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[43]),
    .neuron_ready(neuron_ready_array[43]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd43),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_44.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_44.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_44
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((44+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[44]),
    .neuron_ready(neuron_ready_array[44]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd44),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_45.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_45.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_45
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((45+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[45]),
    .neuron_ready(neuron_ready_array[45]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd45),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_46.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_46.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_46
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((46+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[46]),
    .neuron_ready(neuron_ready_array[46]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd46),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_47.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_47.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_47
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((47+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[47]),
    .neuron_ready(neuron_ready_array[47]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd47),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_48.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_48.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_48
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((48+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[48]),
    .neuron_ready(neuron_ready_array[48]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd48),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_49.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_49.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_49
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((49+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[49]),
    .neuron_ready(neuron_ready_array[49]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd49),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_50.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_50.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_50
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((50+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[50]),
    .neuron_ready(neuron_ready_array[50]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd50),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_51.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_51.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_51
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((51+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[51]),
    .neuron_ready(neuron_ready_array[51]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd51),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_52.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_52.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_52
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((52+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[52]),
    .neuron_ready(neuron_ready_array[52]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd52),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_53.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_53.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_53
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((53+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[53]),
    .neuron_ready(neuron_ready_array[53]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd53),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_54.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_54.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_54
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((54+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[54]),
    .neuron_ready(neuron_ready_array[54]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd54),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_55.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_55.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_55
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((55+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[55]),
    .neuron_ready(neuron_ready_array[55]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd55),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_56.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_56.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_56
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((56+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[56]),
    .neuron_ready(neuron_ready_array[56]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd56),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_57.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_57.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_57
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((57+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[57]),
    .neuron_ready(neuron_ready_array[57]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd57),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_58.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_58.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_58
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((58+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[58]),
    .neuron_ready(neuron_ready_array[58]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd58),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_59.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_59.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_59
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((59+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[59]),
    .neuron_ready(neuron_ready_array[59]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd59),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_60.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_60.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_60
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((60+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[60]),
    .neuron_ready(neuron_ready_array[60]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd60),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_61.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_61.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_61
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((61+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[61]),
    .neuron_ready(neuron_ready_array[61]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd61),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_62.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_62.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_62
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((62+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[62]),
    .neuron_ready(neuron_ready_array[62]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd62),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

neuron
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_FILE("weights/weight_file_layer_1_neuron_63.mem"),
    .BIAS_FILE("biases/bias_file_layer_1_neuron_63.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_63
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((63+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[63]),
    .neuron_ready(neuron_ready_array[63]),
    .cfg_write_enable(cfg_write_enable && cfg_neuron == 6'd63),
    .cfg_is_bias(cfg_is_bias),
    .cfg_weight_addr(cfg_index[WEIGHT_ADDRESS_WIDTH-1:0]),
    .cfg_write_data(cfg_write_data)
);

endmodule
