
module layer_2
#(
  parameter
  DATA_WIDTH            = 16,
  WEIGHT_WIDTH          = 16,
  N_WEIGHTS             = 784, 
  N_NEURONS             = 30,
  N_INPUTS              = 784,
  SIGMOID_INPUT_WIDTH   = 5,
  ACC_TYPE              = "reLU",
  WEIGHT_INT_WIDTH      = 1,
  BIAS_WIDTH            = 32
)
(
  input                              clk,
  input                              reset,
  input                              input_valid,
  input      [DATA_WIDTH-1:0]        input_value,
  output [(DATA_WIDTH*N_NEURONS)-1:0] output_values,
  output                        outputs_valid, 
  output                        layer_ready
);

wire [N_NEURONS-1:0]               outputs_valid_array;
wire [N_NEURONS-1:0]               neuron_ready_array; 
assign outputs_valid = &outputs_valid_array; 
assign layer_ready  = &neuron_ready_array; 



neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_0.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_0.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_0
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((0+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[0]), 
    .neuron_ready(neuron_ready_array[0])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_1.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_1.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_1
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((1+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[1]), 
    .neuron_ready(neuron_ready_array[1])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_2.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_2.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_2
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((2+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[2]), 
    .neuron_ready(neuron_ready_array[2])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_3.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_3.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_3
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((3+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[3]), 
    .neuron_ready(neuron_ready_array[3])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_4.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_4.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_4
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((4+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[4]), 
    .neuron_ready(neuron_ready_array[4])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_5.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_5.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_5
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((5+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[5]), 
    .neuron_ready(neuron_ready_array[5])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_6.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_6.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_6
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((6+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[6]), 
    .neuron_ready(neuron_ready_array[6])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_7.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_7.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_7
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((7+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[7]), 
    .neuron_ready(neuron_ready_array[7])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_8.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_8.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_8
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((8+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[8]), 
    .neuron_ready(neuron_ready_array[8])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_9.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_9.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_9
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((9+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[9]), 
    .neuron_ready(neuron_ready_array[9])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_10.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_10.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_10
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((10+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[10]), 
    .neuron_ready(neuron_ready_array[10])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_11.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_11.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_11
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((11+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[11]), 
    .neuron_ready(neuron_ready_array[11])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_12.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_12.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_12
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((12+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[12]), 
    .neuron_ready(neuron_ready_array[12])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_13.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_13.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_13
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((13+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[13]), 
    .neuron_ready(neuron_ready_array[13])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_14.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_14.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_14
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((14+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[14]), 
    .neuron_ready(neuron_ready_array[14])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_15.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_15.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_15
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((15+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[15]), 
    .neuron_ready(neuron_ready_array[15])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_16.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_16.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_16
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((16+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[16]), 
    .neuron_ready(neuron_ready_array[16])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_17.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_17.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_17
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((17+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[17]), 
    .neuron_ready(neuron_ready_array[17])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_18.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_18.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_18
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((18+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[18]), 
    .neuron_ready(neuron_ready_array[18])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_19.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_19.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_19
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((19+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[19]), 
    .neuron_ready(neuron_ready_array[19])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_20.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_20.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_20
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((20+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[20]), 
    .neuron_ready(neuron_ready_array[20])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_21.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_21.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_21
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((21+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[21]), 
    .neuron_ready(neuron_ready_array[21])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_22.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_22.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_22
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((22+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[22]), 
    .neuron_ready(neuron_ready_array[22])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_23.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_23.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_23
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((23+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[23]), 
    .neuron_ready(neuron_ready_array[23])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_24.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_24.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_24
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((24+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[24]), 
    .neuron_ready(neuron_ready_array[24])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_25.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_25.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_25
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((25+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[25]), 
    .neuron_ready(neuron_ready_array[25])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_26.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_26.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_26
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((26+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[26]), 
    .neuron_ready(neuron_ready_array[26])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_27.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_27.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_27
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((27+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[27]), 
    .neuron_ready(neuron_ready_array[27])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_28.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_28.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_28
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((28+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[28]), 
    .neuron_ready(neuron_ready_array[28])
);

neuron 
#(
    .DATA_WIDTH(DATA_WIDTH),
    .WEIGHT_WIDTH(WEIGHT_WIDTH),
    .N_WEIGHTS(N_WEIGHTS),
    .SIGMOID_INPUT_WIDTH(SIGMOID_INPUT_WIDTH),
    .ACC_TYPE(ACC_TYPE),
    .WEIGHT_INT_WIDTH(WEIGHT_INT_WIDTH),
    .WEIGHT_FILE("weights/weight_file_layer_2_neuron_29.mem"),
    .BIAS_FILE("biases/bias_file_layer_2_neuron_29.mem"),
    .BIAS_WIDTH(BIAS_WIDTH)
)
    NEURON_29
(
    .clk(clk),
    .reset(reset),
    .x_value(input_value),
    .x_valid(input_valid),
    .neuron_output(output_values[(((29+1)*DATA_WIDTH)-1)-:DATA_WIDTH]),
    .output_valid_flag(outputs_valid_array[29]), 
    .neuron_ready(neuron_ready_array[29])
);


endmodule
